### ISSUE TITLE
Visualization of the estimated motion flow.

### ISSUE THREAD

**Issue by sz3623** [ttlzfhy/D-DPCC#4]
Motion prediction between frames is implicit in your experiments.

class inter_prediction(nn.Module):
    ...
    ...
    def forward(self, f1, f2, stride=8, training=True):
        # motion estimation
        merged_f = merge_two_frames(f1, f2)
        out1 = self.relu(self.conv1(merged_f))
        e_o = self.relu(self.conv2(out1))
        ref = self.conv_ref(f2)
        e_c = self.down1(e_o, ref)
        u1 = self.up2(e_c, e_o)
        delta_e = e_o - u1
        e_f = self.down2(delta_e, ref)
        e = e_c + e_f

The dimension of the tensor "e" in the code is 64, so how the scene flow in the form of three-dimensional coordinate offset in Figure 7 is calculated？

**Comment by ttlzfhy** [comment]
Please refer to '3D Adaptively Weighted Interpolation' in Section 3.3 of the paper, and '3DAWI' of model_utils.py. The tensor 'e' is only a fused flow embedding (e_t in the paper). The explicit motion vector is generated in MMR of the motion compensation submodule, i.e. m_t in the paper and 'motion' in the code. It is 192-dimensional, equivalent to the 3-dimensional motion vectors for all the 64 dimensions of the feature yt.

**Comment by sz3623** [comment]
Thank you for your reply. It means that each dimensional feature has a 3D motion vector. In Figure 7, did you take the motion vector of a certain dimension or the average of all dimensions for visualization?

**Comment by ttlzfhy** [comment]
We randomly selected a certain channel for visualization.  In fact, most of the channels of the motion vector look similar.

**Comment by sz3623** [comment]
👍🏻👍🏻👍🏻
