### ISSUE TITLE
what experimental settings the test results in the 'results_csv' directory were obtained?

### ISSUE THREAD

**Issue by Meltryllis111** [ttlzfhy/D-DPCC#5]
Could you please confirm if the test results in the 'pycharm/DDPCC-new-version/results_csv' directory were obtained using the models from the 'pycharm/DDPCC-new-version/ddpcc_ckpts' directory? Were both training and testing dataset using Vox10 data? What are the differences between 'dpcc_100' and 'dpcc_32'? thank you

**Comment by ttlzfhy** [comment]
1. Yes
2. dpcc_100 and 32 correspond to the average results of the first 100 frames and 32 frames of the test sequences, respectively.
